theme = "sonokai"

[editor]
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "diagnostics"]
center = ["file-name"]
right = ["selections", "file-type", "file-encoding", "position-percentage", "position"]

[keys.normal]
g = { a = "code_action", o = "goto_last_accessed_file" }
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
D = "delete_char_backward"
"minus" = { w = ":reflow 130", r = ["open_above", ":pipe echo '#include <>'", "goto_line_end",], b = ["open_below", ":pipe echo '{'", "open_below", ":pipe echo '}'", "normal_mode", "move_line_up"], g = ["open_above", ":pipe echo '#ifndef HEADER_-_ALREAD_INCLUDED'", "open_below", ":pipe echo '#define HEADER_-_ALREAD_INCLUDED'", "open_below", "open_below", "open_below", "open_below", "open_below", ":pipe echo '#endif'", "normal_mode", "goto_file_start", "move_next_word_start", "move_next_word_start", "move_next_word_start", "copy_selection_on_next_line", "change_selection"], s = ["goto_line_end", ":insert-output echo -n 'namespace - { '", "move_line_down", "goto_line_start", ":insert-output echo -n '} '", "normal_mode", "move_line_up", "goto_line_end", "move_prev_word_start", "move_prev_word_start", "trim_selections", "change_selection"], n = ["open_below", ":pipe echo 'MSS_BEGIN(bool);'", "open_below", ":pipe echo 'MSS_END();'", "normal_mode", "move_line_up", "goto_line_end", "move_prev_word_start", "move_prev_word_start"], m = ["open_below", ":pipe echo 'MSS();'", "goto_line_end", "move_char_left"], c = ["open_below", ":pipe echo 'class  '", "indent", "open_below", ":pipe echo '{'", "indent", "open_below", ":pipe echo 'public:'", "open_below", ":pipe echo 'private:'", "open_below", ":pipe echo '};'", "move_line_up", "move_line_up", "move_line_up", "move_line_up", "goto_line_end"] }
C-q = ":buffer-close"

[keys.insert]
C-space = "completion"
# Move cursor in insert mode
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"
A-o = "open_below"
A-O = "open_above"
