#!/usr/bin/env ruby
ARGV.each do |arg|
    case arg
    when '--'
    else
        system('nvr', '--remote-tab', arg)
        system('wmctrl -a Neovim')
        # system('nvim', arg)
        # system('kak', arg)
    end
end
