#!/usr/bin/ruby

context = `task _get rc.context`
context = nil if context.empty?

if ARGV.empty?
    system("task")
else
    args = ARGV.dup
    case args[0]
    when 'add'
        args[0] = ['add', "+#{context}"] if context
    end
    system("task #{args.flatten*' '}")
    system('task list')
end
