source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "alexherbo2/prelude.kak"
plug "alexherbo2/auto-pairs.kak"
plug "alexherbo2/connect.kak"
plug "alexherbo2/search-highlighter.kak"
plug "alexherbo2/volatile-highlighter.kak"
plug "andreyorst/fzf.kak"
plug "kak-lsp/kak-lsp" do %{
 cargo install --locked --force --path .
}
plug "occivink/kakoune-find"

require-module auto-pairs
auto-pairs-enable

require-module connect

require-module search-highlighter
search-highlighter-enable
require-module volatile-highlighter
volatile-highlighter-enable

map global normal <c-p> ': fzf-mode<ret>'

add-highlighter global/ number-lines
add-highlighter global/ wrap

set-option global grepcmd 'rg --column'

#Auto-save on focus-lost
hook global FocusOut .* %{ wa }

hook global BufCreate .+\.naft %{ set buffer filetype naft }
hook global BufSetOption filetype=naft %{
 set-option buffer formatcmd 'kaka'
}
