source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "alexherbo2/prelude.kak"
plug "alexherbo2/auto-pairs.kak"
plug "alexherbo2/connect.kak"
plug "andreyorst/fzf.kak"
plug "kak-lsp/kak-lsp" do %{
 cargo install --locked --force --path .
}
plug "occivink/kakoune-find"

enable-auto-pairs

require-module connect

# Only works under tmux
map global normal <c-p> ': fzf-mode<ret>'

add-highlighter global/ number-lines
add-highlighter global/ wrap

set-option global grepcmd 'rg --column'

#Auto-save on focus-lost
hook global FocusOut .* %{ wa }

hook global BufCreate .+\.naft %{ set buffer filetype naft }
hook global BufSetOption filetype=naft %{
 set-option buffer formatcmd 'kaka'
}

hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}

map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object e '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object k '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

# Copy-paste to clipboard
map global user y '<a-|>xclip -i -selection clipboard<ret>'
map global user p '!xclip -selection clipboard -o<ret>'

hook global BufSetOption filetype=cpp %{
    map buffer user n 'oMSS_BEGIN(bool);<esc>oMSS_END();<esc>k'
    map buffer user m 'oMSS();<esc>hhi'
}

map global normal <c-c> ': comment-line<ret>'

colorscheme gruvbox-dark
