#!/usr/bin/ruby

require('open3')

folder = ARGV.shift

# Upload: from here to s3://
cmd = ['aws', 's3', 'sync', folder, "s3://#{folder}"]+ARGV

puts("Running '#{cmd*' '}'")
Open3.popen2(*cmd) do |_stdin, stdout, wait_thr|
    while line = stdout.gets
        line.chomp!
        puts line
    end

    status = wait_thr.value
    puts(status)
    if status.success?
        exit(0)
    end
end

