#!/usr/bin/ruby

require('open3')

file_or_folder = ARGV.shift

# Upload: from here to s3://
cmd = if File.directory?(file_or_folder)
          ['aws', 's3', 'sync', file_or_folder, "s3://#{file_or_folder}"] + ARGV
      else
          ['aws', 's3', 'cp', file_or_folder, "s3://#{file_or_folder}"] + ARGV
      end

puts("Running '#{cmd * ' '}'")
Open3.popen2(*cmd) do |_stdin, stdout, wait_thr|
    while (line = stdout.gets)
        line.chomp!
        puts line
    end

    status = wait_thr.value
    puts(status)
    exit(0) if status.success?
end
