#!/usr/bin/env ruby

ENV['gubg'] = "#{ENV['HOME']}/gubg" unless ENV.has_key?('gubg')
gubg = ENV['gubg']

filepath, linenr = nil, 0
case ARGV.size
when 1
    filepath = ARGV[0]
when 2 then
    filepath = ARGV[1]
    linenr = ARGV[0][1..]
end

editor = (ENV['gubg_gg'] || :kak).to_sym()

case editor
when :gvim
    system("gvim --remote-tab-silent #{linenr} \"#{filepath}\" 2> /dev/null")
    system("wmctrl -a GVIM")
when :vim, :nvim
    system("#{editor} #{linenr} \"#{filepath}\"")
when :nvr
    system("nvr --remote-tab \"#{filepath}\"")
when :subl
    system("subl \"#{filepath}\":#{linenr}")
when :kak
    system("kak +#{linenr} #{filepath}")
when :kakr
    system("echo eval -client client0 edit #{File.absolute_path(filepath)} #{linenr} | kak -p main")
    system("wmctrl -a ' - Kakoune'")
when :hx
    system("hx -c #{File.join(gubg, 'gubg.tools/src/helix/config.toml')} \"#{filepath}\"")
else raise("Unknown editor #{hx}")
end
