#!/usr/bin/env ruby
ENV["gubg"] = "#{ENV["HOME"]}/gubg" unless ENV.has_key?("gubg")
case :subl
when :gvim
    case ARGV.size
    when 1 then system("gvim --remote-tab-silent \"#{ARGV[0]}\" 2> /dev/null")
    when 2 then system("gvim --remote-tab-silent \"+#{ARGV[1]}\" #{ARGV[0]} 2> /dev/null")
    end
    system("wmctrl -a GVIM")
when :nvim
    case ARGV.size
    when 1 then system("nvim \"#{ARGV[0]}\"")
    when 2 then system("nvim \"+#{ARGV[1]}\" #{ARGV[0]}")
    end
when :nvr
    case ARGV.size
    when 1 then system("nvr --remote-tab \"#{ARGV[0]}\"")
    end
when :subl
    case ARGV.size
    when 1 then system("subl \"#{ARGV[0]}\"")
    end
end
