#!/usr/bin/env ruby

# Launched apps for solus/budgie
# Add custom keybinding to 'home/geertf/gubg/bin/launch firefox' to launch firefox
# Use filename of Gnome .desktop file

require('open3')

module My
    def self.run(cmd)
        output, status = Open3.capture2e(cmd)
        output
    end
end

app = ARGV.shift

could_activate = false

My.run("xdotool search --onlyvisible --class #{app}").split("\n").map(&:to_i).each do |id|
    if !My.run("xdotool windowactivate #{id}")['failed']
        could_activate = true
        break
    end
end

if !could_activate
    `gtk-launch #{app}`
end
