#!/usr/bin/ruby

require('open3')

if :combine_argv_into_resolved_filenames
    fns = []

    fn = nil
    ARGV.each do |part|
        if fn
            fn += " #{part}"
        else
            fn = part
        end

        if File.exist?(fn)
            fns << fn
            fn = nil
        end
    end
    raise("Error: Could not find '#{fn}' on file system") if fn
end

cmd = []

cmd = %w[tar xzvf] if cmd.empty? && fns.size == 1 && fns[0][/\.tar\.gz$/]

if cmd.empty?
    cmd << if RUBY_PLATFORM.include?("darwin")
               'open'
           else
               'xdg-open'
           end
end

cmd += fns

Open3.capture2e(*cmd)
